Add missing Query import from FastAPI
Fix NameError: name 'Query' is not defined
The Query parameter was used in the list_databases endpoint but not imported.

Error:
  File athena_routes.py, line 665
    format: str = Query("angular", ...)
    NameError: name 'Query' is not defined

Fix:
  Added Query to imports from fastapi on line 10